///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, Adaptive Application Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : rawdata.cpp
/// SOFTWARE COMPONENT NAME           : RawData
/// GENERATED DATE                    : 2024-11-12 08:42:40
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "sensor/aa/port/rawdata.h"
 
namespace deepracer
{
namespace service
{
namespace rawdata
{
namespace skeleton
{
 
SvRawDataSkeletonImpl::SvRawDataSkeletonImpl(ara::core::InstanceSpecifier instanceSpec, ara::com::MethodCallProcessingMode mode)
    : SvRawDataSkeleton(instanceSpec, mode)
    , m_logger(ara::log::CreateLogger("SENS", "PORT", ara::log::LogLevel::kVerbose))
{
}
 
} /// namespace skeleton
} /// namespace rawdata
} /// namespace service
} /// namespace deepracer

namespace sensor
{
namespace aa
{
namespace port
{
 
RawData::RawData()
    : m_logger(ara::log::CreateLogger("SENS", "PORT", ara::log::LogLevel::kVerbose))
    , m_running{false}
    , m_REventData{{0U, 0U, 0U}, {0U, 0U, 0U}, {0.0f, 0.0f, 0.0f}}
{
}
 
RawData::~RawData()
{
}
 
void RawData::Start()
{
    m_logger.LogVerbose() << "RawData::Start";
    
    // construct skeleton
    ara::core::InstanceSpecifier specifier{"Sensor/AA/RawData"};
    m_interface = std::make_shared<deepracer::service::rawdata::skeleton::SvRawDataSkeletonImpl>(specifier);
    
    // offer service
    auto offer = m_interface->OfferService();
    if (offer.HasValue())
    {
        m_running = true;
        m_logger.LogVerbose() << "RawData::Start::OfferService";
    }
    else
    {
        m_running = false;
        m_logger.LogError() << "RawData::Start::OfferService::" << offer.Error().Message();
    }
}
 
void RawData::Terminate()
{
    m_logger.LogVerbose() << "RawData::Terminate";
    
    // stop port
    m_running = false;
    
    // stop offer service
    m_interface->StopOfferService();
    m_logger.LogVerbose() << "RawData::Terminate::StopOfferService";
}
 
void RawData::WriteDataREvent(const deepracer::service::rawdata::skeleton::events::REvent::SampleType& data)
{
    std::lock_guard<std::mutex> lock(m_mutex);
    m_REventData = data;
}
 
void RawData::SendEventREventCyclic()
{
    while (m_running)
    {
        {
            std::lock_guard<std::mutex> lock(m_mutex);
            auto send = m_interface->REvent.Send(m_REventData);
            if (send.HasValue())
            {
                m_logger.LogVerbose() << "RawData::SendEventREventCyclic::Send";
            }
            else
            {
                m_logger.LogError() << "RawData::SendEventREventCyclic::Send::" << send.Error().Message();
            }
        }
        std::this_thread::sleep_for(std::chrono::seconds(3));
//제어주기변경하기(sensor.cpp의 데이터 할당 주기와 맞춰 주면 될듯)
    }
}
 
void RawData::SendEventREventTriggered()
{
    std::lock_guard<std::mutex> lock(m_mutex);
    auto send = m_interface->REvent.Send(m_REventData);
    if (send.HasValue())
    {
        m_logger.LogVerbose() << "RawData::SendEventREventTriggered::Send";
    }
    else
    {
        m_logger.LogError() << "RawData::SendEventREventTriggered::Send::" << send.Error().Message();
    }
}
 
void RawData::SendEventREventTriggered(const deepracer::service::rawdata::skeleton::events::REvent::SampleType& data)
{
    std::lock_guard<std::mutex> lock(m_mutex);
    m_REventData = data;
    auto send = m_interface->REvent.Send(m_REventData);
    if (send.HasValue())
    {
        m_logger.LogVerbose() << "RawData::SendEventREventTriggered::Send";
    }
    else
    {
        m_logger.LogError() << "RawData::SendEventREventTriggered::Send::" << send.Error().Message();
    }
}
 
} /// namespace port
} /// namespace aa
} /// namespace sensor
 
/// EOF